name: File Check CI

on:
  push:

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if file exists
        run: |
          if [ -f "data.txt" ]; then
            echo "File found"
          else
            echo "File missing"
          fi
